[tool.briefcase]
project_name = "Smart Playlist"
bundle = "com.tylermoen"
version = "0.0.2"
url = "https://tylermoen.com/smartplaylist"
license = "GNU General Public License v3 (GPLv3)"
author = 'Tyler Moen'
author_email = "tylermmoen@gmail.com"

[tool.briefcase.app.smartplaylist]
formal_name = "Smart Playlist"
description = "A Spotify app that creates group playlists based on a set of user's selected playlists."
icon = "src/smartplaylist/resources/smartplaylist"
sources = ['src/smartplaylist']
requires = []


[tool.briefcase.app.smartplaylist.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.smartplaylist.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.smartplaylist.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.smartplaylist.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.smartplaylist.android]
requires = [
    'toga-android>=0.3.0.dev20',
    'spotipy>=2.19'
]
